image: etna/drone-php
env:
  - APPLICATION_ENV=drone
script:
  - mkdir -p tmp/keys
  - openssl genrsa  -out tmp/keys/private.key 2048
  - openssl rsa -in tmp/keys/private.key -pubout -out tmp/keys/public.key
  - composer install --dev --prefer-source
  - composer phing
  - composer coveralls
notify:
  slack:
    webhook_url: $$SLACK_WEBHOOK_URL
    username: drone
    channel: $$SLACK_CHANNEL
    on_started: true
    on_failure: true
    on_success: true
